### ISSUE TITLE
Not found error

### ISSUE THREAD

**Issue by oroojlooy** [Chacha-Chen/MPLight#1]
Hi,
It seems that either the `README` or the repository are not update. When I follow the instruction, I get:
```
python -O run_batch.py
python: can't open file 'run_batch.py': [Errno 2] No such file or directory

```
Beside, when I directly call `runexp.py`, I get:
```
python runexp.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "runexp.py", line 1, in <module>
    import config
  File "/net/ge.unx.sas.com/vol/vol110/u11/aforoo/traffic/MPLight/config.py", line 12, in <module>
    from dgn_agent import DGNAgent
ModuleNotFoundError: No module named 'dgn_agent'
```
Would you mind take a look?

**Comment by Chacha-Chen** [comment]
Hi, I'll update the README when I got time. 

If you are interested in applying RL in a multi-agent scenario, I recommend you look into these two repos: 1. https://github.com/wingsweihua/presslight  2. https://github.com/wingsweihua/colight

**Comment by oroojlooy** [comment]
Thanks for the quick response. 
I was able to run presslight, but was interested to MPLight since it has smaller state definition. 
Beside, in the paper there is not any point about `SumoEnv`, although the code can either use Sumo or CityFlow. Did you use `Sumo` in the experiments?

**Comment by Chacha-Chen** [comment]
I used Cityflow (anon_env.py). 
The state definition is quite similar to PressLight. I just replaced the lane-num-vehicles to delta-lane-num-vehicles (the discrepancy of the vehicle number in the current lane and its downstream lane).  You could find the implementation at the anon_env.py.
