### ISSUE TITLE
ModuleNotFoundError: No module named 'dgn_agent'

### ISSUE THREAD

**Issue by agbulutonur** [Chacha-Chen/MPLight#10]
Hello,

I headed here after having read your paper [chacha-AAAI2020](https://chacha-chen.github.io/files/chacha-AAAI2020.pdf) and would like to run the code, however I received ModuleNotFoundError: No module named 'dgn_agent' error whenever I try to run project with `python -O run_baseline.py` or `python -O runexp.py` commands.

**Comment by ConnLiu** [comment]
Hello,
same problem for me, so how to solve this?

**Comment by agbulutonur** [comment]
Hello @Chacha-Chen 
Why is this closed? Can you link to solution if it s resolved?

**Comment by Chacha-Chen** [comment]
Hi, I'm sorry I can't update the repo soon. For RL traffic signal control, please refer to https://github.com/wingsweihua/gym_cityflow or https://github.com/wingsweihua/presslight (similar model as thousandLight) instead. Those are actively maitained.

**Comment by krayF1sh** [comment]
> 

Hey there, how did you solve this?
