### ISSUE TITLE
Is manhattan data real data?

### ISSUE THREAD

**Issue by BackMountainDevil** [Chacha-Chen/MPLight#18]
#14 ask about how to run manhattan data but not a  solution.

But when I read about [Manhattan Mobility Model](https://en.wikipedia.org/wiki/Manhattan_mobility_model). If it is generated by Manhattan Mobility Model, that means it is a virtual data.

So is it a virtual data?

**Comment by Chacha-Chen** [comment]
Yea it is virtual.

**Comment by BackMountainDevil** [comment]
Thanks for your kindly reply. Is it generated from CityFlow Generator? Quite different from CityFlow Generator example, which has the same num lanes and it is MxN. Manhattan data is not a regular MxN.

**Comment by BackMountainDevil** [comment]
> Yea it is virtual.

I read [Toward A Thousand Lights: Decentralized Deep Reinforcement Learning for Large-Scale Traffic Signal Control](https://ojs.aaai.org/index.php/AAAI/article/view/5744). 

1. You use `Real-world data` in paper
2. The roadnet is from OpenStreetMap and the raffic flow data from TLC. TLC says that data provided by TPEP/LPEP.

This confuse me. So they are not a virtual data?

**Comment by Chacha-Chen** [comment]
As far as I can recall, the roadmap is somewhat real transformed from
OpenStreetMap. But the traffic data is virtual and we tried variations of
different sized traffic flow.

**Comment by BackMountainDevil** [comment]
Thank you for your kindly explaination. It is helpful to run the data. Best wishes.
