### ISSUE TITLE
"No module named 'dgn_agent'"

### ISSUE THREAD

**Issue by dmitrykazhdan** [Chacha-Chen/MPLight#2]
When trying to run "runexp.py", the following error is thrown: "ImportError: No module named 'dgn_agent'"

In the config.py file, there are imports from DGNAgent and GCNAgent files, which are not in this repo.

**Comment by Chacha-Chen** [comment]
Hi, I'll update the README when I got time.

If you are interested in applying RL in a multi-agent scenario, I recommend you look into these two repos: 1. https://github.com/wingsweihua/presslight 2. https://github.com/wingsweihua/colight
