### ISSUE TITLE
"PHASE" definition on the runexp.py

### ISSUE THREAD

**Issue by oroojlooy** [Chacha-Chen/MPLight#6]
I am a bit confused about the `["PHASE"]` definition in the code. I assume the definition of the `"PHASE"` matches with the definition of phases in the paper:
![image](https://user-images.githubusercontent.com/20797260/79151748-ff4da100-7d98-11ea-9e69-8b4e84e28a16.png)
Right? 
And, I think `WS=WT`, `ES=ET`, ...., right? In this case, why phase-8 which (`SL`, `ST`) represents south-to-north and south-to-west, is denoted by `NLNS`?

Then, my main question is `WS` means toward west, right? In other word, does it represents the traffic movement `road_2_1_2_1` to `road_1_1_2_0/road_1_1_2_1`? Similarly, `WL_WS` represents traffic movements: 
`road_2_1_2_1` to `road_1_1_2_0/road_1_1_2_1` and `road_2_1_2_0` to `road_1_1_3_0/road_1_1_3_1`
Right? 

`dic_traffic_env_conf_extra["PHASE"]["anon"] = {
                    # 0: [0, 0, 0, 0, 0, 0, 0, 0],
                    1: [0, 1, 0, 1, 0, 0, 0, 0],# 'WSES',
                    2: [0, 0, 0, 0, 0, 1, 0, 1],# 'NSSS',
                    3: [1, 0, 1, 0, 0, 0, 0, 0],# 'WLEL',
                    4: [0, 0, 0, 0, 1, 0, 1, 0],# 'NLSL',
                    5: [1, 1, 0, 0, 0, 0, 0, 0],# 'WL_WS'
                    6: [0, 0, 1, 1, 0, 0, 0, 0],# 'EL_ES'
                    7: [0, 0, 0, 1, 0, 0, 1, 1],# 'SL_SS'
                    8: [0, 0, 0, 0, 1, 1, 0, 0] # 'NLNS'
                }`

            `"list_lane_order": ["WL", "WT", "EL", "ET", "SL", "ST", "NL", "NT"],`

Beside, by searching inside the code I found that it is only used in:
`
self.list_phases = dic_traffic_env_conf["PHASE"][dic_traffic_env_conf['SIMULATOR_TYPE']]
`
And `self.list_phase` is only used in:
`self.next_phase_to_set_index = (self.current_phase_index + 1) % len(self.list_phases)`. 
Is this the only usage of "PHASE"?

**Comment by Chacha-Chen** [comment]
WL means west lane left turning phase. WT means west lane straight going phase. Others are similar.

**Comment by oroojlooy** [comment]
So, does `WT` represent the traffic movement `road_2_1_2_1` to `road_1_1_2_0/road_1_1_2_1`?

**Comment by Chacha-Chen** [comment]
road_2_1_2_1 to road_1_1_2_0/road_1_1_2_1/road_1_1_2_3. I remember that there were 3 lanes in each road.

**Comment by oroojlooy** [comment]
Yes, you are right, it also need `road_1_1_2_3`. 
Thanks.
