### ISSUE TITLE
the eng.so

### ISSUE THREAD

**Issue by oroojlooy** [Chacha-Chen/MPLight#7]
I could not find the `engine.so` file among the files in the repository. Would you mind add it to the repository?

**Comment by Chacha-Chen** [comment]
engine.so is useless.

**Comment by oroojlooy** [comment]
But, in `anon_env.py`, I see that `engine` is imported, and not the cityflow. I tried `import cityflow as engine`, but it does not work with `anon_env` since the API of cityflow are changed in the recent version. Am I missing something?

**Comment by Chacha-Chen** [comment]
No. The reason is that I worked on an older version of Cityflow (2 years ago). Please fix the API accordingly with your version of Cityflow.

**Comment by oroojlooy** [comment]
I see, thanks for clarification.
