### ISSUE TITLE
flow file for customized roadnet file

### ISSUE THREAD

**Issue by zhuliwen** [Chacha-Chen/MPLight#8]
Hello, thank you for this code, I am a bit confused, how do you generate a flow file for your **customized roadnet file**？ In the `generate_grid_scenario.py` file CityFlow provided, I see that the format of the generated route is `road_%d_%d_%d`, but the route I want to generate is composed of my edges in the roadnet file, just like `"569345515#1"` or `"569345515#2"` in Manhattan flow file,
Is there any code for this conversion in cityflow?

**Comment by Chacha-Chen** [comment]
Hi Liwen,

There are 2 ways to generate the flow and the roadnet file. 
1. synthetic (generate_grid_scenario)
2. convert form the SUMO or open street map roadnet. (manhattan)

Find more detail here. https://cityflow.readthedocs.io/en/latest/roadnet.html

**Comment by zhuliwen** [comment]
Thank you!

**Comment by mainakchain** [comment]
How to create flow file for real OSM road network? I already created my roadnet file from sumo net.xml file. But I am not sure how to obtain the corresponding flow file. In the **generate_grid_scenario.py** file, the script expects rowNum and colNum but for real world scenario, how to yield that? @Chacha-Chen @zhuliwen

**Comment by LuckyLeeLL** [comment]
> How to create flow file for real OSM road network? I already created my roadnet file from sumo net.xml file. But I am not sure how to obtain the corresponding flow file. In the **generate_grid_scenario.py** file, the script expects rowNum and colNum but for real world scenario, how to yield that? @Chacha-Chen @zhuliwen

i have the same question that can not confirm the rownum and colnum, how did you solve it?
